In [97]:
import pandas as pd
data = pd.read_csv("markndata.csv")
data

     student_id   tam   eng   math  science  social  total grade
0           1.0  69.0  51.0   47.0     79.0    49.0    NaN     F
1           2.0  79.0   NaN   65.0     43.0    70.0  309.0     D
2           3.0  43.0  64.0  100.0     36.0    84.0  327.0     D
3           4.0  85.0  54.0   91.0     57.0     NaN  330.0     D
4           NaN  98.0  78.0   59.0     51.0     NaN  350.0     C
..          ...   ...   ...    ...      ...     ...    ...   ...
495       496.0  49.0   NaN   36.0      NaN    90.0  261.0   NaN
496       497.0  61.0  69.0   57.0     95.0    77.0  359.0     C
497       498.0  50.0   NaN   77.0     74.0    75.0  312.0     D
498       499.0  63.0   NaN   50.0     81.0    91.0    NaN     C
499       500.0   NaN  90.0   74.0     53.0    63.0  354.0     C

[500 rows x 8 columns]

In [98]:
data.head(10)

   student_id   tam   eng   math  science  social  total grade
0         1.0  69.0  51.0   47.0     79.0    49.0    NaN     F
1         2.0  79.0   NaN   65.0     43.0    70.0  309.0     D
2         3.0  43.0  64.0  100.0     36.0    84.0  327.0     D
3         4.0  85.0  54.0   91.0     57.0     NaN  330.0     D
4         NaN  98.0  78.0   59.0     51.0     NaN  350.0     C
5         6.0  94.0   NaN   79.0     45.0    53.0  371.0     C
6         7.0  53.0  91.0   36.0     80.0    50.0  310.0     D
7         NaN  42.0   NaN   57.0     49.0    99.0  319.0     D
8         9.0  54.0  54.0   47.0      NaN    43.0  233.0     F
9         NaN  99.0  61.0   69.0     73.0     NaN  398.0     C

In [99]:
data.tail(10)

     student_id   tam   eng  math  science  social  total grade
490       491.0  58.0  36.0  38.0     92.0     NaN  265.0     F
491       492.0  44.0  90.0  90.0     65.0    43.0  332.0     D
492       493.0  71.0  75.0  84.0     99.0    36.0    NaN     C
493       494.0   NaN  42.0  83.0     38.0    36.0    NaN     F
494       495.0  42.0  95.0  77.0     46.0    62.0    NaN   NaN
495       496.0  49.0   NaN  36.0      NaN    90.0  261.0   NaN
496       497.0  61.0  69.0  57.0     95.0    77.0  359.0     C
497       498.0  50.0   NaN  77.0     74.0    75.0  312.0     D
498       499.0  63.0   NaN  50.0     81.0    91.0    NaN     C
499       500.0   NaN  90.0  74.0     53.0    63.0  354.0     C

In [100]:
data.describe()

,student_id,tam,eng,math,science,social,total
count,450.000000,441.000000,432.000000,456.00000,455.000000,450.000000,440.000000
mean,256.382222,67.052154,65.076389,67.14693,67.683516,66.051111,334.840909
std,143.333929,19.052547,19.045341,19.12924,19.293606,18.584055,41.533390
min,1.000000,35.000000,35.000000,35.00000,35.000000,35.000000,221.000000
25%,134.500000,51.000000,49.000000,50.00000,51.000000,50.000000,307.750000
50%,257.500000,67.000000,64.000000,68.00000,68.000000,65.000000,336.000000
75%,380.750000,84.000000,81.250000,83.25000,85.000000,81.750000,362.000000
max,500.000000,100.000000,100.000000,100.00000,100.000000,100.000000,437.000000

In [101]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  450 non-null    float64
 1   tam         441 non-null    float64
 2   eng         432 non-null    float64
 3   math        456 non-null    float64
 4   science     455 non-null    float64
 5   social      450 non-null    float64
 6   total       440 non-null    float64
 7   grade       450 non-null    object
dtypes: float64(7), object(1)
memory usage: 31.4+ KB

In [102]:
data.isnull()

     student_id    tam    eng   math  science  social  total  grade
0         False  False  False  False    False   False   True  False
1         False  False   True  False    False   False  False  False
2         False  False  False  False    False   False  False  False
3         False  False  False  False    False    True  False  False
4          True  False  False  False    False    True  False  False
..          ...    ...    ...    ...      ...     ...    ...    ...
495       False  False   True  False     True   False  False   True
496       False  False  False  False    False   False  False  False
497       False  False   True  False    False   False  False  False
498       False  False   True  False    False   False   True  False
499       False   True  False  False    False   False  False  False

[500 rows x 8 columns]

In [103]:
data.isnull().sum()

student_id    50
tam           59
eng           68
math          44
science       45
social        50
total         60
grade         50
dtype: int64

In [104]:
xs =data["studentid"].median()
print(xs)
data["studentid"].fillna(xs, inplace=True)

KeyError: 'studentid'

In [105]:
x11 =data["tam"].mean()
print(x11)

67.05215419501134

In [106]:
data["tam"].fillna(data["tam"].mean(), inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_3792\4050955756.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["tam"].fillna(data["tam"].mean(), inplace=True)

In [107]:
x12 =data["eng"].mean()
print(x12)

65.07638888888889

In [108]:
data["eng"].fillna(x12, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_3792\2074844808.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["eng"].fillna(x12, inplace=True)

In [109]:
x13 =data["math"].mean()
print(x13)

67.1469298245614

In [110]:
data["math"].fillna(x13, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_3792\2319610617.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["math"].fillna(x13, inplace=True)

In [111]:
x14 =data["science"].mean()
print(x14)

67.68351648351648

In [112]:
data["science"].fillna(x14, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_3792\2568950359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["science"].fillna(x14, inplace=True)

In [113]:
x15 =data["social"].mean()
print(x15)

66.05111111111111

In [114]:
data["social"].fillna(x15, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_3792\1914929754.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["social"].fillna(x15, inplace=True)

In [115]:
x16 =data["total"].mean()
print(x16)

334.84090909090907

In [116]:
data["total"].fillna(x16, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_3792\2782192157.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["total"].fillna(x16, inplace=True)

In [117]:
x17 =data["grade"].mode()[0]
print(x17)
data["grade"].fillna(x17, inplace=True)

D

C:\Users\user\AppData\Local\Temp\ipykernel_3792\499124639.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["grade"].fillna(x17, inplace=True)

In [118]:
data["grade"].replace("D", "Poor", inplace =True)
data

,student_id,tam,eng,math,science,social,total,grade
0,1.0,69.000000,51.000000,47.0,79.000000,49.000000,334.840909,F
1,2.0,79.000000,65.076389,65.0,43.000000,70.000000,309.000000,Poor
2,3.0,43.000000,64.000000,100.0,36.000000,84.000000,327.000000,Poor
3,4.0,85.000000,54.000000,91.0,57.000000,66.051111,330.000000,Poor
4,NaN,98.000000,78.000000,59.0,51.000000,66.051111,350.000000,C
...,...,...,...,...,...,...,...,...
495,496.0,49.000000,65.076389,36.0,67.683516,90.000000,261.000000,Poor
496,497.0,61.000000,69.000000,57.0,95.000000,77.000000,359.000000,C
497,498.0,50.000000,65.076389,77.0,74.000000,75.000000,312.000000,Poor
498,499.0,63.000000,65.076389,50.0,81.000000,91.000000,334.840909,C
499,500.0,67.052154,90.000000,74.0,53.000000,63.000000,354.000000,C

In [119]:
data.replace("F", "Very Poor")

,student_id,tam,eng,math,science,social,total,grade
0,1.0,69.000000,51.000000,47.0,79.000000,49.000000,334.840909,Very Poor
1,2.0,79.000000,65.076389,65.0,43.000000,70.000000,309.000000,Poor
2,3.0,43.000000,64.000000,100.0,36.000000,84.000000,327.000000,Poor
3,4.0,85.000000,54.000000,91.0,57.000000,66.051111,330.000000,Poor
4,NaN,98.000000,78.000000,59.0,51.000000,66.051111,350.000000,C
...,...,...,...,...,...,...,...,...
495,496.0,49.000000,65.076389,36.0,67.683516,90.000000,261.000000,Poor
496,497.0,61.000000,69.000000,57.0,95.000000,77.000000,359.000000,C
497,498.0,50.000000,65.076389,77.0,74.000000,75.000000,312.000000,Poor
498,499.0,63.000000,65.076389,50.0,81.000000,91.000000,334.840909,C
499,500.0,67.052154,90.000000,74.0,53.000000,63.000000,354.000000,C

In [120]:
# column selection
data["tam"]

0      69.000000
1      79.000000
2      43.000000
3      85.000000
4      98.000000
         ...
495    49.000000
496    61.000000
497    50.000000
498    63.000000
499    67.052154
Name: tam, Length: 500, dtype: float64

In [121]:
# Multi column selection
data[["tam","eng","math","grade"]]

           tam        eng   math grade
0    69.000000  51.000000   47.0     F
1    79.000000  65.076389   65.0  Poor
2    43.000000  64.000000  100.0  Poor
3    85.000000  54.000000   91.0  Poor
4    98.000000  78.000000   59.0     C
..         ...        ...    ...   ...
495  49.000000  65.076389   36.0  Poor
496  61.000000  69.000000   57.0     C
497  50.000000  65.076389   77.0  Poor
498  63.000000  65.076389   50.0     C
499  67.052154  90.000000   74.0     C

[500 rows x 4 columns]

In [122]:
# condition filtering
data[data["grade"] == "Poor"]

,student_id,tam,eng,math,science,social,total,grade
1,2.0,79.0,65.076389,65.0,43.000000,70.000000,309.000000,Poor
2,3.0,43.0,64.000000,100.0,36.000000,84.000000,327.000000,Poor
3,4.0,85.0,54.000000,91.0,57.000000,66.051111,330.000000,Poor
6,7.0,53.0,91.000000,36.0,80.000000,50.000000,310.000000,Poor
7,NaN,42.0,65.076389,57.0,49.000000,99.000000,319.000000,Poor
...,...,...,...,...,...,...,...,...
488,489.0,56.0,59.000000,53.0,80.000000,70.000000,334.840909,Poor
491,492.0,44.0,90.000000,90.0,65.000000,43.000000,332.000000,Poor
494,495.0,42.0,95.000000,77.0,46.000000,62.000000,334.840909,Poor
495,496.0,49.0,65.076389,36.0,67.683516,90.000000,261.000000,Poor
497,498.0,50.0,65.076389,77.0,74.000000,75.000000,312.000000,Poor

In [123]:
data.sort_values("total")

,student_id,tam,eng,math,science,social,total,grade
375,376.0,38.000000,36.000000,45.00000,61.000000,41.0,221.0,Poor
367,368.0,51.000000,42.000000,67.14693,35.000000,59.0,222.0,F
248,249.0,67.052154,62.000000,41.00000,45.000000,36.0,223.0,F
449,450.0,44.000000,37.000000,41.00000,42.000000,65.0,229.0,F
8,9.0,54.000000,54.000000,47.00000,67.683516,43.0,233.0,F
...,...,...,...,...,...,...,...,...
32,33.0,97.000000,71.000000,67.14693,99.000000,83.0,423.0,B
101,102.0,61.000000,94.000000,93.00000,88.000000,88.0,424.0,B
201,202.0,84.000000,96.000000,98.00000,90.000000,57.0,425.0,B
484,485.0,85.000000,65.076389,93.00000,74.000000,96.0,437.0,B
89,90.0,99.000000,50.000000,96.00000,94.000000,98.0,437.0,B

In [124]:
data.sort_values("total", ascending = False)

,student_id,tam,eng,math,science,social,total,grade
89,90.0,99.000000,50.000000,96.00000,94.000000,98.0,437.0,B
484,485.0,85.000000,65.076389,93.00000,74.000000,96.0,437.0,B
201,202.0,84.000000,96.000000,98.00000,90.000000,57.0,425.0,B
101,102.0,61.000000,94.000000,93.00000,88.000000,88.0,424.0,B
32,33.0,97.000000,71.000000,67.14693,99.000000,83.0,423.0,B
...,...,...,...,...,...,...,...,...
8,9.0,54.000000,54.000000,47.00000,67.683516,43.0,233.0,F
449,450.0,44.000000,37.000000,41.00000,42.000000,65.0,229.0,F
248,249.0,67.052154,62.000000,41.00000,45.000000,36.0,223.0,F
367,368.0,51.000000,42.000000,67.14693,35.000000,59.0,222.0,F
375,376.0,38.000000,36.000000,45.00000,61.000000,41.0,221.0,Poor

In [125]:
data.groupby("grade").sum()

,student_id,tam,eng,math,science,social,total
grade,,,,,,,
B,5619.0,2204.208617,2087.305556,2320.440789,2239.417582,2178.051111,11131.840909
C,33007.0,9815.678005,9293.680556,9948.763158,9941.619780,9773.715556,48822.250000
F,19573.0,4959.469388,5088.993056,5089.322368,5188.151648,5162.255556,25802.454545
Poor,57173.0,16546.721088,16068.215278,16214.938596,16472.569231,15911.533333,81663.909091

In [126]:
data.groupby("grade")["total"].mean()

grade
B       412.290404
C       367.084586
F       286.693939
Poor    326.655636
Name: total, dtype: float64

In [127]:
data["Avg"] = data['total'] / 5
data

,student_id,tam,eng,math,science,social,total,grade,Avg
0,1.0,69.000000,51.000000,47.0,79.000000,49.000000,334.840909,F,66.968182
1,2.0,79.000000,65.076389,65.0,43.000000,70.000000,309.000000,Poor,61.800000
2,3.0,43.000000,64.000000,100.0,36.000000,84.000000,327.000000,Poor,65.400000
3,4.0,85.000000,54.000000,91.0,57.000000,66.051111,330.000000,Poor,66.000000
4,NaN,98.000000,78.000000,59.0,51.000000,66.051111,350.000000,C,70.000000
...,...,...,...,...,...,...,...,...,...
495,496.0,49.000000,65.076389,36.0,67.683516,90.000000,261.000000,Poor,52.200000
496,497.0,61.000000,69.000000,57.0,95.000000,77.000000,359.000000,C,71.800000
497,498.0,50.000000,65.076389,77.0,74.000000,75.000000,312.000000,Poor,62.400000
498,499.0,63.000000,65.076389,50.0,81.000000,91.000000,334.840909,C,66.968182
499,500.0,67.052154,90.000000,74.0,53.000000,63.000000,354.000000,C,70.800000

In [128]:
cols = ["tam","eng","math","science","social","total","Avg"]
data[cols] = data[cols].round().astype(int)

In [131]:
data.to_html("output1.html")